### ISSUE TITLE
Fix styling for logseq-tocgen

### ISSUE THREAD

**Issue by mlaguayojr** [andyburris/logseq-arc-theme#19]
I noticed the following styling issue with logseq-tocgen while using either the arc dark or the arc light theme.

Screenshot of arc dark theme being used:
![Screenshot 2023-01-06 221932](https://user-images.githubusercontent.com/10964526/211130368-4918a918-2d13-45f9-a8f6-d7e2c8b76575.png)

Screenshot of arc light theme being used:
![Screenshot 2023-01-06 221954](https://user-images.githubusercontent.com/10964526/211130369-aa6cd654-a6d4-4b40-8eb9-d91be462c3b4.png)

Below is a screenshot of tocgen rendered while using the default logseq dark theme:
![Screenshot 2023-01-06 221858](https://user-images.githubusercontent.com/10964526/211130359-52f1a442-04de-4137-91a5-f19b78725cc4.png)

I poked around in inspector and came up with the following CSS to hopefully resolve this:
```css
div[id^="logseq-tocgen--"] > div > div > div > div > span, 
div[id^="logseq-tocgen--"] > div > div > div > div > button {
  padding: 0 !important;
  display: inline !important;
}
```

Screenshot of above CSS applied through `custom.css` on arc dark theme:
![Screenshot 2023-01-06 230531](https://user-images.githubusercontent.com/10964526/211130602-3df4ba1b-e54e-4100-b243-3a5930f71dc1.png)
